[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
molecule = { path = "../.." }
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
base64 = "0.21"
anyhow = "1.0"
tracing = "0.1.41"
